"""add exclude_perfect_settings to users

Revision ID: 10ede6c189ee
Revises: 
Create Date: 2026-02-17 21:17:36.377818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ede6c189ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('current_level', sa.String(length=20), nullable=True),
    sa.Column('remind_window_days', sa.Integer(), nullable=False),
    sa.Column('exclude_perfect_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vocab',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocab_day'), 'vocab', ['day'], unique=False)
    op.create_index(op.f('ix_vocab_difficulty_level'), 'vocab', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_vocab_word'), 'vocab', ['word'], unique=False)
    op.create_table('level_cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('cycle_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_level_cycles_difficulty_level'), 'level_cycles', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_level_cycles_user_id'), 'level_cycles', ['user_id'], unique=False)
    op.create_table('level_day_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('cycle_no', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_level_day_progress_day'), 'level_day_progress', ['day'], unique=False)
    op.create_index(op.f('ix_level_day_progress_difficulty_level'), 'level_day_progress', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_level_day_progress_user_id'), 'level_day_progress', ['user_id'], unique=False)
    op.create_table('study_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('cycle_no', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('studied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_logs_cycle_no'), 'study_logs', ['cycle_no'], unique=False)
    op.create_index(op.f('ix_study_logs_difficulty_level'), 'study_logs', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_study_logs_user_id'), 'study_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_study_logs_vocab_id'), 'study_logs', ['vocab_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('cycle_no', sa.Integer(), nullable=False),
    sa.Column('leitner_level', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('is_mastered', sa.Boolean(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('correct_streak', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_cycle_no'), 'user_progress', ['cycle_no'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_progress_vocab_id'), 'user_progress', ['vocab_id'], unique=False)
    op.create_table('vocab_examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('example_en', sa.Text(), nullable=True),
    sa.Column('example_kr', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocab_examples_vocab_id'), 'vocab_examples', ['vocab_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocab_examples_vocab_id'), table_name='vocab_examples')
    op.drop_table('vocab_examples')
    op.drop_index(op.f('ix_user_progress_vocab_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_cycle_no'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_study_logs_vocab_id'), table_name='study_logs')
    op.drop_index(op.f('ix_study_logs_user_id'), table_name='study_logs')
    op.drop_index(op.f('ix_study_logs_difficulty_level'), table_name='study_logs')
    op.drop_index(op.f('ix_study_logs_cycle_no'), table_name='study_logs')
    op.drop_table('study_logs')
    op.drop_index(op.f('ix_level_day_progress_user_id'), table_name='level_day_progress')
    op.drop_index(op.f('ix_level_day_progress_difficulty_level'), table_name='level_day_progress')
    op.drop_index(op.f('ix_level_day_progress_day'), table_name='level_day_progress')
    op.drop_table('level_day_progress')
    op.drop_index(op.f('ix_level_cycles_user_id'), table_name='level_cycles')
    op.drop_index(op.f('ix_level_cycles_difficulty_level'), table_name='level_cycles')
    op.drop_table('level_cycles')
    op.drop_index(op.f('ix_vocab_word'), table_name='vocab')
    op.drop_index(op.f('ix_vocab_difficulty_level'), table_name='vocab')
    op.drop_index(op.f('ix_vocab_day'), table_name='vocab')
    op.drop_table('vocab')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
